/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vehicle_DSP_YZ_VehicleTransit_CVS */

#ifndef _Included_vehicle_DSP_YZ_VehicleTransit_CVS
#define _Included_vehicle_DSP_YZ_VehicleTransit_CVS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vehicle_DSP_YZ_VehicleTransit_CVS
 * Method:    capitalize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vehicle_1DSP_YZ_1VehicleTransit_1CVS_capitalize
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
